language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - "composer self-update"
  - "composer --version"
  - "composer install --no-dev --no-interaction --prefer-dist"

script:
  - "phpunit -c phpunit.xml.dist"
